apiVersion: apps/v1
kind: Deployment
metadata:
  name: selectstore
  labels:
    app: selectstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selectstore
  template:
    metadata:
      labels:
        app: selectstore
    spec:
      containers:
        - name: selectstore
          image: username/selectstore:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
